#jhodgeskumabundle_default:
#    resource: "@JHodgesKumaBundle/Controller/DefaultController.php"
#    type:     annotation
#    prefix:   /

jhodges_dashboard:
    resource: "@JHodgesKumaBundle/Controller/DashboardController.php"
    type:     annotation
    prefix:   /admin/dashboard
