name: "Slider + Three column page (equal)"
rows:
    - regions:
        - { name: "slider", span: 12 }
    - regions:
        - { name: "left_column", span: 4 }
        - { name: "main", span: 4 }
        - { name: "right_column", span: 4 }
    - regions:
        - { name: "footer", span: 12 }
template: "JHodgesKumaBundle::Pages\\Common\\three-column-equal-slider-pagetemplate.html.twig"
