name: "Two column page (left sidebar)"
rows:
    - regions:
        - { name: "header", span: 12 }
    - regions:
        - { name: "left_column", span: 3 }
        - { name: "main", span: 9 }
    - regions:
        - { name: "footer", span: 12 }
template: "JHodgesKumaBundle::Pages\\Common\\two-column-left-pagetemplate.html.twig"